### ISSUE TITLE
Configurable Keybindings

### ISSUE THREAD

**Issue by stormdragon2976** [bmmcginty/barnard#1]
Would it be possible to make it so that keybindings for the different actions can be configured and stored in a file? Of course the keybindings file would be optional, and without it, the defaults would be used.

**Comment by bmmcginty** [comment]
I believe this can be done.
How about something like this?

```
ptt f1
toggle_timestamps alt+t
switch_view tab
exit f10
volume_down f5
volume_up f6
```

**Comment by stormdragon2976** [comment]
That sounds great. The only thing I would say is maybe use one of the standard assignment layouts like:

ptt = "f1"

Or even yaml style as in:

ptt: "f1"

**Comment by bmmcginty** [comment]
When running the newest push of Barnard, you'll have hotkeys written to .barnard.yaml in your home directory.
You can edit those once you close Barnard.
All the keys and commands are lowercase.
Per-user volume is also persisted in that yaml file.
I've updated the Readme as well.
Documentation suggestions are welcome.

**Comment by stormdragon2976** [comment]
Thanks so much for adding this. I was just wondering how to assign a key combination like alt+t? I tried \et, alt+t, and alt,t but they all failed to parse correctly.

**Comment by bmmcginty** [comment]
The alt key is treated oddly. Let me work on this tonight; for now, you can use the Control key with a bunch of the keys (ctrl_f1, ctrl_t, etc).
Sorry about this; I somehow overlooked this the other day.

**Comment by bmmcginty** [comment]
Give the latest push a shot.
alt_t and alt_f3 work for me hear, now, as examples.

**Comment by bmmcginty** [comment]
closing this as complete. Please reopen/open another issue if anything is unclear.
